### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by fer-rum** [fsr/ifsr_course_enrollment#14]
The project needs a proper license to be usable for others without being left in the dark of legel issues concering additions, usage or creation of derivates.

It is suggested to use a GPL license, but others like BSD or MIT would be fine too.

**Comment by fer-rum** [comment]
The license has been decided to be GPL 3.0. Now all left to do is implement it.

**Comment by JustusAdam** [comment]
Why GPL 3?

If I may ask?

**Comment by dmuhs** [comment]
The [GPLv3](http://www.gnu.org/copyleft/gpl.html) doesn't look too bad in the [summary](https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29). There isn't much to discuss as we just want to preserve the rights to keep it open-source and let it freely be modified and distributed, right? I don't know how relevant commercial use or sublicensing are for our appliance.
However, there seem to be some [good reasons](http://www.gnu.org/licenses/rms-why-gplv3.html) to upgrade from GPLv2.

**Comment by JustusAdam** [comment]
I'm more of a GPLv2 guy but I'm preparing the pull request right now

**Comment by JustusAdam** [comment]
Pull request is on the table

**Comment by fer-rum** [comment]
Merging #18 closes this issue.

**Comment by fer-rum** [comment]
Merging #19 incorporates license fine-tuning.
