### ISSUE TITLE
Generated URLs are malformed after re-visiting site

### ISSUE THREAD

**Issue by fer-rum** [fsr/ifsr_course_enrollment#16]
**Steps to reproduce:**
1) Login as Organizer and create a course.
2) Logout and return to the home page. Note how the link to the new course points to _localhost/kurse__/kurse__/1/indexapp/_
3) Quit the session, delete all cookies and browser cache.
4) Re-visit the home page. Note that the link now points to _localhost/kurse/1/indexapp_ which will not resolve properly.

**Potential causes:**
This is most likely a combination of programming and configuration errors.

**Impact:**
This prevents effective use of the system by visitors.

**Comment by fer-rum** [comment]
This problem magically seems not to appear if you have been logged in beforehand and not closed your session since.

**Comment by fer-rum** [comment]
Nevermind, this happens seemingly randomly.
I wonder if this is due to caching either in the browser or on the server side.

**Comment by JustusAdam** [comment]
Perhaps this happens since the /kurse/kurse urls are botched and weird anyway? Don't we have a more general problem there anyway?

**Comment by fer-rum** [comment]
This is related to #5.

**Comment by fer-rum** [comment]
It was a problem with the deployment configuration. Fixed now.
