### ISSUE TITLE
Providing no accreditation prevents enrolment

### ISSUE THREAD

**Issue by fer-rum** [fsr/ifsr_course_enrollment#31]
If a user provides no accreditation (because none is needed) a confirmation link will not be created and the enrolment process is aborted.

**Comment by JustusAdam** [comment]
Does it cause an exception?

**Comment by fer-rum** [comment]
No. It simply refers to the same page and nothing happens.

**Comment by JustusAdam** [comment]
Before I change the code. Do you _want_ it to not be required?

**Comment by fer-rum** [comment]
No. Only restriction: If you chose accreditation, a faculty is required. There is a table what can be accredited for whom, but I am not sure if you want to implement it at this point as well.
